# Generated by Django 6.0.2 on 2026-02-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('budget_min_amd', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max_amd', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('draft', 'Draft')], default='public', max_length=20)),
                ('response_price_credits', models.PositiveIntegerField(default=1)),
                ('responses_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_job_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('credits_balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_provider_profile',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price_amd', models.PositiveIntegerField(blank=True, null=True)),
                ('timeline_text', models.TextField(blank=True)),
                ('cover_message', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('response_fee_credits', models.PositiveIntegerField(default=1)),
                ('viewed_by_client_at', models.DateTimeField(blank=True, null=True)),
                ('decision_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='marketplace.jobrequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_response',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'provider')},
            },
        ),
    ]
