# Generated by Django 6.0.2 on 2026-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
