# Generated by Django 6.0.2 on 2026-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_allow_blank_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', editable=False, max_length=32, unique=True)),
                ('default_response_price_credits', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Marketplace settings',
                'verbose_name_plural': 'Marketplace settings',
                'db_table': 'marketplace_marketplace_settings',
            },
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('draft', 'Draft'), ('verified_only', 'Verified only')], default='public', max_length=20),
        ),
    ]
