# Generated by Django 6.0.2 on 2026-02-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_add_marketplace_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('repair', 'Repair'), ('construction', 'Construction'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='city',
            field=models.CharField(choices=[('yerevan', 'Yerevan'), ('gyumri', 'Gyumri'), ('vanadzor', 'Vanadzor'), ('abovyan', 'Abovyan'), ('ejmiatsin', 'Ejmiatsin'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
