# Generated by Django 6.0.2 on 2026-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_seed_marketplace_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='open', max_length=20),
        ),
    ]
