# Generated by Django 6.0.2 on 2026-02-26 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_provider_profile_week2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'marketplace_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'marketplace_city',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='portfolio',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='city_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='marketplace.city'),
        ),
    ]
