# Generated by Django 6.0.2 on 2026-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_add_client_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
